version: "3.8"

services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_PORT_NUMBER: 2181
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: bitnami/kafka:3.9
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BROKER}
    ports:
      - "9092:9092"
    restart: always

  fastapi_app:
    build: .
    container_name: fastapi_app
    depends_on:
      - postgres_db
      - kafka
    environment:
      DATABASE_URL: ${DATABASE_URL}
      KAFKA_BROKER: ${KAFKA_BROKER}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always

volumes:
  db_data:

networks:
  default:
    driver: bridge
